### ISSUE TITLE
Logo and Icon Design For Basket Manager

### ISSUE THREAD

**Issue by zularizal** [mattia-atzeni/basket-manager#1]
Hi @mattia-atzeni , I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. It's free for your project. What do you think?

**Comment by mattia-atzeni** [comment]
Hi @zularizal, thank you for your interest in this project! Any contribution is welcome and I would really appreciate your help. So, feel free to design new logo / icons for this project!

**Comment by zularizal** [comment]
Hi, I've designed some logos, what do you think? Which one do you like?
If there is something you want to change please let me know.

![logo](https://user-images.githubusercontent.com/38547278/42065276-3b8d3970-7b64-11e8-80b8-13353ce67763.png)

**Comment by mattia-atzeni** [comment]
Hi @zularizal! Thanks, you did an impressive work! Probably my favorite is the last one. Can you put it into a white circle or in a white box with rounded corners? I think it would look great as the main icon of the app!

**Comment by zularizal** [comment]
Do you mean like this? Right or left?

![rect2225](https://user-images.githubusercontent.com/38547278/42102482-2ef87e90-7bf0-11e8-9af2-8ec0a0235043.png)

**Comment by mattia-atzeni** [comment]
I think that the left one looks great as the main icon of the app.

**Comment by zularizal** [comment]
Hi, I've uploaded the logo to the drive, this is the link

https://drive.google.com/open?id=1X-7lQ8sKE1JaMBQd-rfRVN8lcY74Qn5I

and also I have sent a pull request for you, check #2

**Comment by mattia-atzeni** [comment]
Thanks, I merged the pull request!
